import { Link, WorkExperience, Skill, Education, Project, Language, Song } from './types';

export const personalInfo = {
  name: 'Lars Dehairs',
  profession: 'Radiomaker & Podcaster',
  location: 'Zottegem, Belgium',
  social: '@larsdehairs',
  email: 'radio.larsdehairs@outlook.com',
  avatar: 'https://i1.sndcdn.com/avatars-3IyrCUUQ66HX9j4I-yW6mHg-t240x240.jpg',
};

export const bio = "I’m Lars Dehairs, a radiomaker and podcaster from Zottegem, Belgium. I enjoy creating radio shows and podcasts that connect with people, whether it’s music, stories, or conversations that make someone’s day a bit better. Over the past few years, I’ve learned a lot from hands-on experience behind the mic, in the studio, and during live broadcasts. I like working with sound, exploring new ideas, and learning how to make each show a little better than the last.";

const ACCENT_COLOR = '#0071e3';

export const personalLinks: Link[] = [
  { name: 'Instagram', url: 'https://www.instagram.com/larsdehairs/profilecard/?igsh=MWQ1Nnlrd2Zua2p4eQ%3D%3D', icon: 'Instagram', description: 'Personal Profile', color: '#E4405F' },
  { name: 'Soundcloud', url: 'https://soundcloud.com/lars-dehairs', icon: 'Soundcloud', description: 'Personal Projects & Mixes', color: '#FF5500' },
  { name: 'Email (Radio)', url: 'mailto:radio.larsdehairs@outlook.com', icon: 'Envelope', description: 'For radio-related inquiries', color: ACCENT_COLOR },
  { name: 'Email (Other)', url: 'mailto:lars.dehairs@gmail.com', icon: 'Envelope', description: 'For other inquiries', color: ACCENT_COLOR },
];

export const projects: Project[] = [
  {
    name: 'Tom Tom Talks',
    description: 'A podcast where drummers talk about their lives, careers, and the drummers who inspire them. Hosted by Lars Dehairs, this show dives deep into the world of rhythm and percussion.',
    links: [
      { name: 'Website', url: 'https://tomtomtalks.boenkerz.be/', icon: 'Website', description: 'Official podcast website', color: '#374151' },
      { name: 'Instagram', url: 'https://www.instagram.com/tom_tom_talks', icon: 'Instagram', description: "Podcast's Instagram", color: '#E4405F' },
      { name: 'Apple Podcasts', url: 'https://podcasts.apple.com/us/podcast/tom-tom-talks/id1847627374', icon: 'ApplePodcasts', description: 'Listen on Apple Podcasts', color: '#A259FF' },
      { name: 'Spotify', url: 'https://open.spotify.com/show/1GyOwlJX6Q8POKlPNa45As?si=5a23e3820c124120', icon: 'Spotify', description: 'Listen on Spotify', color: '#1DB954' },
      { name: 'Email', url: 'mailto:tomtomtalks.podcast@gmail.com', icon: 'Envelope', description: 'Contact the podcast', color: ACCENT_COLOR },
    ]
  },
  {
    name: 'Boenkerz',
    description: "An online radio station and creative platform based in Ghent, Belgium. Lars hosts several shows on Boenkerz, including 'De Pauzeknop', bringing fresh sounds and interesting conversations to the airwaves.",
    links: [
      { name: 'Website', url: 'https://boenkerz.be', icon: 'Website', description: 'Broadcasting platform', color: '#374151' },
      { name: 'Pauzeknop Email (Program)', url: 'mailto:boenkerz.pauzeknop@gmail.com', icon: 'Envelope', description: 'Contact my radio program', color: ACCENT_COLOR },
    ]
  }
];

export const workExperience: WorkExperience[] = [
  {
    role: 'Radiomaker',
    company: 'Boenkerz',
    period: '2022 – Present',
    tasks: [
      'Presentatie 11–12u zaterdag — Boenkerz Gent',
      'Presentatie Headbang Hour — time TBD',
      'Presentatie De Pauzeknop — time TBD',
    ],
  },
  {
    role: 'Podcaster',
    company: 'Tom Tom Talks',
    period: '2025 – Present',
    tasks: [
      'Host of “Tom Tom Talks”, a podcast about drummers and their favourite drummers.',
    ],
  },
  {
    role: 'Radiomaker',
    company: 'Urgent.fm via Blooshoofd',
    period: '2022 – 2024',
    tasks: ['Presentatie zaterdag: 12–13u'],
  },
];

export const skills: Skill[] = [
  { name: 'Presenting', icon: 'Mic', url: '#', color: ACCENT_COLOR },
  { name: 'Interviewing', icon: 'Comments', url: '#', color: ACCENT_COLOR },
  { name: 'Editing', icon: 'Scissors', url: '#', color: ACCENT_COLOR },
  { name: 'Improvisation', icon: 'Bolt', url: '#', color: ACCENT_COLOR },
  { name: 'Mixing', icon: 'Sliders', url: '#', color: ACCENT_COLOR },
  { name: 'Voice-over', icon: 'Headphones', url: '#', color: ACCENT_COLOR },
  { name: 'Scripting', icon: 'FileAlt', url: '#', color: ACCENT_COLOR },
  { name: 'Reaper', icon: 'WaveSquare', url: 'https://www.reaper.fm/', color: '#333333' },
  { name: 'Power Studio', icon: 'BroadcastTower', url: 'https://www.power-studio.nl/', color: '#ffc107' },
  { name: 'Zenon Media', icon: 'Radio', url: 'https://www.zenon-media.com/', color: '#d32f2f' },
  { name: 'DaVinci Resolve', icon: 'Film', url: 'https://www.blackmagicdesign.com/products/davinciresolve', color: '#0078d7' },
  { name: 'Canva', icon: 'Palette', url: 'https://www.canva.com/', color: '#00c4cc' },
  { name: 'Spotify', icon: 'Spotify', url: 'https://www.spotify.com/', color: '#1db954' },
  { name: 'FL Studio', icon: 'Music', url: 'https://www.image-line.com/', color: '#ff4500' },
  { name: 'Audacity', icon: 'Waveform', url: 'https://www.audacityteam.org/', color: '#0000a0' },
];

export const languages: Language[] = [
  { name: 'Dutch', level: 'Native' },
  { name: 'English', level: 'Good' },
  { name: 'French', level: 'Okay' },
];

export const education: Education[] = [
  {
    institution: 'Royal Atheneum Zottegem',
    degree: 'Natural Sciences',
    period: '2021 – Present',
  },
];

export const nowPlayingPlaylist: Song[] = [
    { title: "Imagine - Remastered 2010", artist: "John Lennon", album: "Imagine", duration: "03:07", spotifyId: "7pKfPomDEeI4TPT6EOYjn9" },
    { title: "Island In The Sun", artist: "Weezer", album: "Weezer", duration: "03:20", spotifyId: "2MLHyLy5z5l5YRp7momlgw" },
    { title: "Deep in the Willow", artist: "Knocked Loose", album: "Upon Loss Singles", duration: "03:31", spotifyId: "7KbfKTMX3wbQW5OJvIGRdg" },
    { title: "Japam", artist: "Botch", album: "An Anthology of Dead Ends", duration: "02:56", spotifyId: "6fsmhUf5ZsYlO1EhuewCIt" },
    { title: "Seeing Red", artist: "Architects", album: "The Sky, The Earth & All Between", duration: "03:40", spotifyId: "65qBr6ToDUjTD1RiE1H4Gl" },
    { title: "Nerdy", artist: "Poison The Well", album: "The Opposite of December... A Season of Separation", duration: "02:43", spotifyId: "5qonKXM5Uh1I7PB75Xhx86" },
    { title: "Beautiful Boy (Darling Boy) - Remastered 2010", artist: "John Lennon", album: "Double Fantasy", duration: "04:05", spotifyId: "5URfZHMlUWTWxPvvSBWcPk" },
    { title: "Let It Be - Remastered 2009", artist: "The Beatles", album: "Let It Be (Remastered)", duration: "04:03", spotifyId: "7iN1s7xHE4ifF5povM6A48" },
    { title: "BLACKOUT", artist: "Turnstile", album: "GLOW ON", duration: "02:53", spotifyId: "0bGImSqDB2ebdeoCidUC8o" },
    { title: "Black Flame - Single Edit", artist: "Bury Tomorrow", album: "Black Flame", duration: "03:53", spotifyId: "6REc2Tq4G2RW5zKXtusTLF" },
    { title: "Blackbird - Remastered 2009", artist: "The Beatles", album: "The Beatles (Remastered)", duration: "02:18", spotifyId: "5jgFfDIR6FR0gvlA56Nakr" },
    { title: "Thirst", artist: "Knocked Loose", album: "You Won't Go Before You're Supposed To", duration: "01:46", spotifyId: "7wk4CsCdm795itk3Yir8pS" },
    { title: "Killing In The Name", artist: "Rage Against The Machine", album: "Rage Against The Machine - XX (20th Anniversary Special Edition)", duration: "05:13", spotifyId: "59WN2psjkt1tyaxjspN8fp" },
    { title: "My Hero", artist: "Foo Fighters", album: "The Colour And The Shape", duration: "04:20", spotifyId: "4dVbhS6OiYvFikshyaQaCN" },
    { title: "Bulls On Parade", artist: "Rage Against The Machine", album: "Evil Empire", duration: "03:49", spotifyId: "0tZ3mElWcr74OOhKEiNz1x" },
    { title: "Heart-Shaped Box", artist: "Nirvana", album: "In Utero (Deluxe Edition)", duration: "04:41", spotifyId: "11LmqTE2naFULdEP94AUBa" },
    { title: "Say It Ain't So - Original Mix", artist: "Weezer", album: "Weezer", duration: "04:18", spotifyId: "6VoIBz0VhCyz7OdEoRYDiA" },
    { title: "The Man Who Sold The World - Live", artist: "Nirvana", album: "MTV Unplugged In New York", duration: "04:21", spotifyId: "15VRO9CQwMpbqUYA7e6Hwg" },
    { title: "Can't Stop", artist: "Red Hot Chili Peppers", album: "By the Way (Deluxe Edition)", duration: "04:29", spotifyId: "3ZOEytgrvLwQaqXreDs2Jx" },
    { title: "Scar Tissue", artist: "Red Hot Chili Peppers", album: "Californication (Deluxe Edition)", duration: "03:35", spotifyId: "1G391cbiT3v3Cywg8T7DM1" },
    { title: "Under the Bridge", artist: "Red Hot Chili Peppers", album: "Blood Sugar Sex Magik (Deluxe Edition)", duration: "04:24", spotifyId: "3d9DChrdc6BOeFsbrZ3Is0" },
    { title: "By the Way", artist: "Red Hot Chili Peppers", album: "By the Way (Deluxe Edition)", duration: "03:36", spotifyId: "1f2V8U1BiWaC9aJWmpOARe" },
    { title: "About A Girl", artist: "Nirvana", album: "Bleach", duration: "02:48", spotifyId: "2SHTKB8YYlawTGIuJ2b2ok" },
    { title: "White Washed", artist: "August Burns Red", album: "Constellations", duration: "03:46", spotifyId: "0jCUZSnjn6hxp7zgX3h2rF" },
    { title: "Japam", artist: "Botch", album: "An Anthology of Dead Ends", duration: "02:56", spotifyId: "6LgVJ8580266guSFqp124I" },
    { title: "We Come Out At Night", artist: "Avenged Sevenfold", album: "Sounding The Seventh Trumpet", duration: "04:44", spotifyId: "6hJO4kMjKVBiYUNpZTxgYM" },
    { title: "Feel the Pressure", artist: "DRAIN", album: "California Cursed", duration: "03:38", spotifyId: "58z4qdwM0zpWJEGfjSptR7" },
    { title: "Overcome", artist: "Terror", album: "One With The Underdogs", duration: "02:26", spotifyId: "6L4DiyQhMKVtfCJEIA8h42" },
    { title: "Seeing Red", artist: "Architects", album: "Seeing Red", duration: "03:40", spotifyId: "5EauhH7IW4eDo0SPnP6rIY" },
    { title: "New Noise", artist: "Refused", album: "The Shape Of Punk To Come (Deluxe Edition)", duration: "05:10", spotifyId: "35iLpqqQg4KrfYAzbvN1vH" },
    { title: "Guerrilla Radio", artist: "Rage Against The Machine", album: "The Battle Of Los Angeles", duration: "03:26", spotifyId: "1wsRitfRRtWyEapl0q22o8" },
    { title: "Say It Ain't So", artist: "Weezer", album: "Weezer", duration: "04:18", spotifyId: "56MEbUIvvfEEkLIl51wxGD" },
    { title: "Undone - The Sweater Song", artist: "Weezer", album: "Weezer", duration: "05:05", spotifyId: "5WhtlIoxoZrMmuaWWEQhwV" },
    { title: "Rape Me", artist: "Nirvana", album: "In Utero (Deluxe Edition)", duration: "02:50", spotifyId: "5Rizj5FLb2AyNKu9esjYY6" },
    { title: "Dani California", artist: "Red Hot Chili Peppers", album: "Stadium Arcadium", duration: "04:42", spotifyId: "10Nmj3JCNoMeBQ87uw5j8k" },
    { title: "Sabotage", artist: "Beastie Boys", album: "Ill Communication", duration: "02:58", spotifyId: "0Puj4YlTm6xNzDDADXHMI9" },
    { title: "Cigarettes & Alcohol", artist: "Oasis", album: "Definitely Maybe", duration: "04:49", spotifyId: "3nK2qGHdVAEOuVAmMSWQPW" },
    { title: "Monkey Wrench", artist: "Foo Fighters", album: "The Colour And The Shape", duration: "03:51", spotifyId: "44wXefe8WB9Fd6xwtmAwbR" },
    { title: "Piano Man", artist: "Billy Joel", album: "Piano Man (Legacy Edition)", duration: "05:39", spotifyId: "70C4NyhjD5OZUMzvWZ3njJ" },
    { title: "Jealous Guy - Remastered 2010", artist: "John Lennon", album: "Imagine", duration: "04:17", spotifyId: "3D9iV6cYkYJRAPFO6DRKIE" },
    { title: "Yesterday - Remastered 2009", artist: "The Beatles", album: "Help! (Remastered)", duration: "02:05", spotifyId: "3BQHpFgAp4l80e1XslIjNI" },
    { title: "Hotel California - 2013 Remaster", artist: "Eagles", album: "Hotel California (2013 Remaster)", duration: "06:31", spotifyId: "40riOy7x9W7GXjyGp4pjAv" },
    { title: "Here Comes The Sun - Remastered 2009", artist: "The Beatles", album: "Abbey Road (Remastered)", duration: "03:05", spotifyId: "6dGnYIeXmHdcikdzNNDMm2" },
    { title: "Stand By Me - Remastered 2010", artist: "John Lennon", album: "Rock 'N' Roll", duration: "03:31", spotifyId: "3ntrdR24dLkKrzSGRv1FlH" },
    { title: "In My Life - Remastered 2009", artist: "The Beatles", album: "Rubber Soul (Remastered 2009)", duration: "02:26", spotifyId: "3KfbEIOC7YIv90FIfNSZpo" },
    { title: "Woman - Remastered 2010", artist: "John Lennon", album: "Double Fantasy: Stripped Down", duration: "03:32", spotifyId: "0GGxVTb0UwDwdaKNjBdCn3" },
    { title: "Rocket Man (I Think It's Going To Be A Long, Long Time)", artist: "Elton John", album: "Honky Chateau", duration: "04:41", spotifyId: "3gdewACMIVMEWVbyb8O9sY" },
    { title: "Don't Look Back in Anger - Remastered", artist: "Oasis", album: "Time Flies... 1994-2009 (Remastered)", duration: "04:50", spotifyId: "1gYNo6sCys1dJEIFcgqlYr" },
    { title: "My Sweet Lord (2014 Remaster)", artist: "George Harrison", album: "All Things Must Pass (2014 Remaster)", duration: "04:41", spotifyId: "0KZodeWxqxd88F9wY1cqgs" },
    { title: "Sultans Of Swing", artist: "Dire Straits", album: "Dire Straits", duration: "05:48", spotifyId: "37Tmv4NnfQeb0ZgUC4fOJj" },
    { title: "(Just Like) Starting Over - Remastered 2010", artist: "John Lennon", album: "Double Fantasy: Stripped Down", duration: "03:56", spotifyId: "5y0YreEOnQiKFAnCrcFIXz" },
    { title: "House of the Rising Sun", artist: "The Animals", album: "The Singles Plus", duration: "04:29", spotifyId: "4mn2kNTqiGLwaUR8JdhJ1l" },
    { title: "Oh My Love - Remastered 2010", artist: "John Lennon", album: "Imagine", duration: "02:48", spotifyId: "0gDyuX5rdHulQTUyrIdSR1" },
    { title: "Instant Karma! (We All Shine On) - Remastered 2010", artist: "John Lennon, Yoko Ono", album: "Signature Box", duration: "03:20", spotifyId: "2BkXpZSvPoUDMLI2Xw9kAL" },
    { title: "Hey Jude - 2015 Mix", artist: "The Beatles", album: "The Beatles 1967 – 1970 (2023 Edition)", duration: "07:11", spotifyId: "1RP85mAmvJ8baqjP53kFJu" },
    { title: "Give Peace A Chance - Remastered 2010", artist: "John Lennon, Yoko Ono", album: "Signature Box", duration: "04:54", spotifyId: "4iwGGmK8zlbcgkUymPNTVc" },
    { title: "God - Remastered 2010", artist: "John Lennon", album: "Plastic Ono Band", duration: "04:12", spotifyId: "7kipZd4tWx6Mu8kBgB2Z2r" },
    { title: "Eleanor Rigby - Remastered 2009", artist: "The Beatles", album: "Revolver (Remastered)", duration: "02:06", spotifyId: "5GjPQ0eI7AgmOnADn1EO6Q" },
    { title: "Wonderwall - Remastered", artist: "Oasis", album: "Time Flies... 1994-2009 (Remastered)", duration: "04:21", spotifyId: "0A6sqSxlqml1wjQLjuM4BH" },
    { title: "Stairway to Heaven - Remaster", artist: "Led Zeppelin", album: "Led Zeppelin IV (Deluxe Edition)", duration: "08:02", spotifyId: "5CQ30WqJwcep0pYcV4AMNc" },
    { title: "Something - Remastered 2009", artist: "The Beatles", album: "Abbey Road (Remastered)", duration: "03:02", spotifyId: "0pNeVovbiZHkulpGeOx1Gj" },
    { title: "Knockin' On Heaven's Door", artist: "Bob Dylan", album: "Pat Garrett & Billy The Kid (Soundtrack From The Motion Picture)", duration: "02:29", spotifyId: "6HSXNV0b4M4cLJ7ljgVVeh" },
    { title: "Strawberry Fields Forever - Remastered 2009", artist: "The Beatles", album: "Magical Mystery Tour (Remastered)", duration: "04:07", spotifyId: "3Am0IbOxmvlSXro7N5iSfZ" },
    { title: "Wish You Were Here", artist: "Pink Floyd", album: "Wish You Were Here", duration: "05:34", spotifyId: "6mFkJmJqdDVQ1REhVfGgd1" },
    { title: "Happy Together", artist: "The Turtles", album: "Happy Together", duration: "02:56", spotifyId: "1JO1xLtVc8mWhIoE3YaCL0" },
    { title: "Your Song", artist: "Elton John", album: "Elton John", duration: "04:01", spotifyId: "38zsOOcu31XbbYj9BIPUF1" },
    { title: "Somebody To Love - Remastered 2011", artist: "Queen", album: "A Day At The Races (Deluxe Edition 2011 Remaster)", duration: "04:56", spotifyId: "4rDbp1vnvEhieiccprPMdI" },
    { title: "While My Guitar Gently Weeps - Remastered 2009", artist: "The Beatles", album: "The Beatles (Remastered)", duration: "04:45", spotifyId: "389QX9Q1eUOEZ19vtzzI9O" },
    { title: "Crazy Little Thing Called Love - Remastered 2011", artist: "Queen", album: "The Game (2011 Remaster)", duration: "02:43", spotifyId: "6xdLJrVj4vIXwhuG8TMopk" },
    { title: "Live And Let Die - 2018 Remaster", artist: "Wings", album: "Red Rose Speedway (Archive Collection)", duration: "03:12", spotifyId: "0VV8wkOM4w78A2OHZOTzNP" },
    { title: "Comfortably Numb", artist: "Pink Floyd", album: "The Wall", duration: "06:22", spotifyId: "5HNCy40Ni5BZJFw1TKzRsC" },
    { title: "Wouldn't It Be Nice", artist: "The Beach Boys", album: "Pet Sounds", duration: "02:33", spotifyId: "4IHc6SzGPnzSPuHVEPzpJc" },
    { title: "Good Vibrations - Remastered 2001", artist: "The Beach Boys", album: "Smiley Smile (Remastered)", duration: "03:39", spotifyId: "5t9KYe0Fhd5cW6UYT4qP8f" },
    { title: "God Only Knows - Remastered 1996", artist: "The Beach Boys", album: "Pet Sounds", duration: "02:54", spotifyId: "17QTsL4K9B9v4rI8CAIdfC" },
    { title: "Shine On You Crazy Diamond, Pts. 1-5 - 2011 Remastered Version", artist: "Pink Floyd", album: "Wish You Were Here (2011 Remastered Version)", duration: "13:31", spotifyId: "1dtfTodJ3Uld533EXKQokC" },
    { title: "Creep", artist: "Radiohead", album: "Pablo Honey", duration: "03:58", spotifyId: "6b2oQwSGFkzsMtQruIWm2p" },
    { title: "Karma Police", artist: "Radiohead", album: "OK Computer", duration: "04:24", spotifyId: "3SVAN3BRByDmHOhKyIDxfC" },
    { title: "Wish You Were Here", artist: "Pink Floyd", album: "A Collection Of Great Dance Songs", duration: "05:21", spotifyId: "1HzDhHApjdjXPLHF6GGYhu" },
    { title: "Money", artist: "Pink Floyd", album: "The Dark Side of the Moon", duration: "06:22", spotifyId: "0vFOzaXqZHahrZp6enQwQb" },
    { title: "Time", artist: "Pink Floyd", album: "The Dark Side of the Moon", duration: "06:53", spotifyId: "3TO7bbrUKrOSPGRTB5MeCz" },
    { title: "Shine On You Crazy Diamond, Pts. 1-5 - 2011 Remastered Version", artist: "Pink Floyd", album: "Wish You Were Here [2011 - Remaster] (2011 Remastered Version)", duration: "13:31", spotifyId: "2dWCp5vcNwSy25zRVFGC5t" },
    { title: "Shine On You Crazy Diamond (Pts. 6-9)", artist: "Pink Floyd", album: "Wish You Were Here", duration: "12:27", spotifyId: "21j1PsCiTaO8ZW88UZrh3A" },
    { title: "Shine On You Crazy Diamond (Pts. 1-5)", artist: "Pink Floyd", album: "Wish You Were Here", duration: "13:31", spotifyId: "6pnwfWyaWjQiHCKTiZLItr" },
    { title: "Twist And Shout - Remastered 2009", artist: "The Beatles", album: "Please Please Me (Remastered)", duration: "02:35", spotifyId: "5ZBeML7Lf3FMEVviTyvi8l" },
    { title: "I Want To Hold Your Hand - Remastered 2009", artist: "The Beatles", album: "The Beatles 1962 - 1966 (Remastered)", duration: "02:26", spotifyId: "5Qe7NHxeLAn8KoLTNLSdwe" },
    { title: "Come Together - Remastered 2009", artist: "The Beatles", album: "Abbey Road (Remastered)", duration: "04:19", spotifyId: "2EqlS6tkEnglzr7tkKAAYD" },
    { title: "Help! - Remastered 2009", artist: "The Beatles", album: "Help! (Remastered)", duration: "02:19", spotifyId: "7DD7eSuYSC5xk2ArU62esN" },
    { title: "Hey Jude - Remastered 2015", artist: "The Beatles", album: "1 (Remastered)", duration: "07:05", spotifyId: "0aym2LBJBk9DAYuHHutrIl" },
    { title: "Drive My Car - Remastered 2009", artist: "The Beatles", album: "Rubber Soul (Remastered 2009)", duration: "02:28", spotifyId: "06ypiqmILMdVeaiErMFA91" },
    { title: "A Day In The Life - Remastered 2009", artist: "The Beatles", album: "Sgt. Pepper's Lonely Hearts Club Band (Remastered)", duration: "05:37", spotifyId: "0hKRSZhUGEhKU6aNSPBACZ" },
    { title: "Love Me Do - Remastered 2009", artist: "The Beatles", album: "Please Please Me (Remastered)", duration: "02:21", spotifyId: "3VbGCXWRiouAq8VyMYN2MI" },
    { title: "Penny Lane - Remastered 2009", artist: "The Beatles", album: "Magical Mystery Tour (Remastered)", duration: "03:00", spotifyId: "1h04XMpzGzmAudoI6VHBgA" },
    { title: "I Saw Her Standing There - Remastered 2009", artist: "The Beatles", album: "Please Please Me (Remastered)", duration: "02:53", spotifyId: "3KiexfmhxHvG5IgAElmTkd" },
    { title: "The Long And Winding Road - Remastered 2009", artist: "The Beatles", album: "Let It Be (Remastered)", duration: "03:38", spotifyId: "3mlMpmY8oZIBFc39D9zLbh" },
    { title: "Don't Let Me Down - Remastered 2009", artist: "The Beatles", album: "The Beatles 1967 - 1970 (Remastered)", duration: "03:35", spotifyId: "3evG0BIqEFMMP7lVJh1cSf" },
    { title: "She Loves You - Mono / Remastered", artist: "The Beatles", album: "1 (Remastered)", duration: "02:20", spotifyId: "2Fk411Ix3qnMG8t8Qa74ZX" },
    { title: "Californication", artist: "Red Hot Chili Peppers", album: "Californication (Deluxe Edition)", duration: "05:29", spotifyId: "48UPSzbZjgc449aqz8bxox" },
    { title: "Otherside", artist: "Red Hot Chili Peppers", album: "Californication (Deluxe Edition)", duration: "04:15", spotifyId: "64BbK9SFKH2jk86U3dGj2P" },
    { title: "Snow (Hey Oh)", artist: "Red Hot Chili Peppers", album: "Stadium Arcadium", duration: "05:34", spotifyId: "2aibwv5hGXSgw7Yru8IYTO" },
    { title: "Dark Necessities", artist: "Red Hot Chili Peppers", album: "The Getaway", duration: "05:02", spotifyId: "2oaK4JLVnmRGIO9ytBE1bt" },
    { title: "Under Pressure - Remastered 2011", artist: "Queen, David Bowie", album: "Hot Space (2011 Remaster)", duration: "04:08", spotifyId: "2fuCquhmrzHpu5xcA1ci9x" },
    { title: "All Apologies", artist: "Nirvana", album: "In Utero", duration: "03:53", spotifyId: "1Ic9pKxGSJGM0LKeqf6lGe" },
    { title: "High and Dry", artist: "Radiohead", album: "The Bends", duration: "04:17", spotifyId: "2a1iMaoWQ5MnvLFBDv4qkf" },
    { title: "November Rain", artist: "Guns N' Roses", album: "Use Your Illusion I", duration: "08:56", spotifyId: "3YRCqOhFifThpSRFJ1VWFM" },
    { title: "Where Did You Sleep Last Night - Live", artist: "Nirvana", album: "MTV Unplugged In New York", duration: "05:06", spotifyId: "551qy5vUgrUfEUc4dCNfht" },
    { title: "My Curse", artist: "Killswitch Engage", album: "As Daylight Dies (Special Edition)", duration: "04:04", spotifyId: "6zKF4293k44ItKWJJgrhXv" },
    { title: "Afghamistam", artist: "Botch", album: "An Anthology of Dead Ends", duration: "06:56", spotifyId: "4rkVp4yEiLcxjpCyvTZ1Yt" },
    { title: "Abandon Us", artist: "Bury Tomorrow", album: "The Seventh Sun", duration: "03:42", spotifyId: "39KxX34pPo46RD3xVwfWyj" },
    { title: "Man on Fire", artist: "Bury Tomorrow", album: "Runes", duration: "04:01", spotifyId: "2LHtWEncuemszNBtrMfvII" },
    { title: "Boltcutter", artist: "Bury Tomorrow", album: "The Seventh Sun", duration: "03:37", spotifyId: "6Qe4DUWhgMt6cKlOJ5mDhc" },
    { title: "No Less Violent", artist: "Bury Tomorrow", album: "Black Flame", duration: "03:29", spotifyId: "2lH5lV6f57sOiLimUoQ106" },
    { title: "DEATH (Ever Colder)", artist: "Bury Tomorrow", album: "DEATH (Ever Colder)", duration: "04:47", spotifyId: "7tAUrb26TuIeZlVVvn9XdJ" },
    { title: "Animals", artist: "Architects", album: "For Those That Wish To Exist", duration: "04:04", spotifyId: "5ofoB8PFmocBXFBEWVb6Vz" },
    { title: "Doomsday", artist: "Architects", album: "Holy Hell", duration: "04:07", spotifyId: "75R95k0ICuZBFVEjBauOtt" },
    { title: "Keepers of the Faith", artist: "Terror", album: "Keepers Of The Faith", duration: "03:12", spotifyId: "6CkAvo0TDvHRiqH6nJNW9o" },
    { title: "Hard Lessons", artist: "Terror", album: "Live By The Code", duration: "02:43", spotifyId: "05qkrlhuTafAGpDl0qdG39" },
    { title: "Still At War", artist: "Mindwar", album: "Still At War", duration: "01:42", spotifyId: "4kGDEENkyWuMEeWywxfZ6g" },
    { title: "Can We Start Again", artist: "Bane", album: "It All Comes Down to This", duration: "03:19", spotifyId: "36eklRgfCgcYEJISG1S23M" },
    { title: "The Heart from Your Hate", artist: "Trivium", album: "The Sin and the Sentence", duration: "04:03", spotifyId: "5yDJpu0xh0d1w13gXaE3lS" },
    { title: "Concubine", artist: "Converge", album: "Jane Doe", duration: "01:19", spotifyId: "1ui9EPnCqTurWbYICi9Gld" },
    { title: "Hell to Pay", artist: "Converge", album: "Jane Doe", duration: "04:31", spotifyId: "3IP88lVJFVCEClXXJEJfPy" },
    { title: "Invisible Enemy", artist: "August Burns Red", album: "Invisible Enemy", duration: "04:37", spotifyId: "5VCzofkfy3SJWek4NrsUro" },
    { title: "My Last Serenade", artist: "Killswitch Engage", album: "Alive or Just Breathing (Topshelf Edition)", duration: "04:13", spotifyId: "2Ps4FrDiR6JcJfSZbXAPBz" },
    { title: "From Heaven We Fall", artist: "Arkangel", album: "Dead Man Walking", duration: "04:34", spotifyId: "3mKaiYZLeOYJT1u8hoIYMw" },
    { title: "Mistakes Like Fractures", artist: "Knocked Loose", album: "A Different Shade of Blue", duration: "03:39", spotifyId: "1STzQvlMovhX8WOn8TcKmZ" },
    { title: "Mariana's Trench", artist: "August Burns Red", album: "Constellations", duration: "04:18", spotifyId: "5iMPhdSTH7OovnhUzo2juY" },
    { title: "Your Betrayal", artist: "Bullet For My Valentine", album: "Fever", duration: "04:51", spotifyId: "25GC50HslaaruyrKjdu0lP" },
    { title: "Always the Hard Way", artist: "Terror", album: "Always the Hard Way", duration: "02:33", spotifyId: "4uCiDcjH8oAXTEaqzxX5Qm" },
    { title: "Everything is Quiet Now", artist: "Knocked Loose", album: "Upon Loss Singles", duration: "03:35", spotifyId: "6XpWCxEdQDbHygtWnBY9Eu" },
    { title: "Unholy Confessions", artist: "Avenged Sevenfold", album: "Waking The Fallen", duration: "04:43", spotifyId: "20g7z9R1wjE7EtVnB7XEjS" },
    { title: "Endzeit", artist: "Heaven Shall Burn", album: "Iconoclast (Pt. 1: The Final Resistance)", duration: "04:17", spotifyId: "4lFxQyVeTYkM010VUtCp6o" },
    { title: "Within the Walls of Babylon", artist: "Arkangel", album: "Dead Man Walking", duration: "02:20", spotifyId: "4hEzXKB4yZGSO8mOSZNgBC" },
    { title: "Billy No Mates", artist: "Knocked Loose, Counterparts", album: "Laugh Tracks", duration: "02:14", spotifyId: "20Ov9PW41YrzgpGdvbARfE" },
    { title: "Boomslang", artist: "Kublai Khan TX", album: "Absolute", duration: "02:27", spotifyId: "0Tv7bJqFc8YOS5It6Ap4Ug" },
    { title: "Composure", artist: "August Burns Red", album: "Messengers", duration: "04:13", spotifyId: "1NBLKfycJLSpzYM4zYIB8v" },
    { title: "Deadringer", artist: "Knocked Loose", album: "Laugh Tracks", duration: "03:00", spotifyId: "1HD11vDTcCQB2n1pUKSEdc" },
    { title: "Through Struggle", artist: "As I Lay Dying", album: "Shadows Are Security", duration: "03:58", spotifyId: "0fmwyv8VP8Jh71e87oCHv1" },
    { title: "Blackened Sun", artist: "Get The Shot", album: "Infinite Punishment", duration: "03:45", spotifyId: "1jE88GZBfLFkRrlzQhB2DY" },
    { title: "God Knows", artist: "Knocked Loose", album: "A Tear in the Fabric of Life", duration: "03:34", spotifyId: "3idDCx8VXTkqPL6UQTK4bl" },
    { title: "My Will Be Done", artist: "Unearth", album: "The March", duration: "03:37", spotifyId: "76u2aab2a33Ohs7dOKoUOa" },
    { title: "Nihilist", artist: "Architects", album: "All Our Gods Have Abandoned Us", duration: "02:51", spotifyId: "0LnNkDzIGaYKCvGbe5N9Wo" },
    { title: "Human Carrying Capacity", artist: "Harms Way", album: "Posthuman", duration: "03:17", spotifyId: "63C2F8dGaKxdhUW1oVWPlW" },
    { title: "Become a Machine", artist: "Harms Way", album: "Posthuman", duration: "03:12", spotifyId: "6Xt6hMb6cxdZ29ULtdQIFl" },
    { title: "The Hammer", artist: "Kublai Khan TX", album: "Nomad", duration: "03:21", spotifyId: "3xqphesjm6paYsZjBqYSaA" },
    { title: "Self-Destruct", artist: "Kublai Khan TX", album: "Absolute", duration: "02:19", spotifyId: "2eqjpko1AQuTdxkBFhAcRG" },
    { title: "Puppet Master", artist: "Thy Art Is Murder", album: "Dear Desolation", duration: "03:15", spotifyId: "7Ehz2k1K2YJ5xbyAAfaPAa" },
    { title: "Natural Born Killer", artist: "Emmure", album: "Look at Yourself", duration: "02:37", spotifyId: "4dFI3oZOaZn2iSOEUe1FFO" },
    { title: "Solar Flare Homicide", artist: "Emmure", album: "Speaker Of The Dead", duration: "03:50", spotifyId: "6pCkJ0r6WEyz5ASErk5ezS" },
    { title: "Engine 45", artist: "The Ghost Inside", album: "Get What You Give", duration: "04:12", spotifyId: "70SkWedrjKzDgKrqHZwAf4" },
    { title: "Creep", artist: "Alpha Wolf", album: "A Quiet Place to Die", duration: "02:57", spotifyId: "0MLktMbt74tMfIg4tAZqbU" },
    { title: "Death Squad Anthem", artist: "Thy Art Is Murder", album: "Human Target", duration: "03:13", spotifyId: "3xZxgCiuO2UGN6bEmz6ZIu" },
    { title: "Earthbound", artist: "Bury Tomorrow", album: "Earthbound", duration: "03:42", spotifyId: "1DKbMKbzeZ57yo6yI4MeXe" },
    { title: "Forecast", artist: "Kindred", album: "The Final Cut", duration: "02:52", spotifyId: "2E36gTpit00YsrtHwCiiS6" },
    { title: "Carrion", artist: "Parkway Drive", album: "Horizons (Deluxe Edition)", duration: "03:07", spotifyId: "0xfWKcNu13xxXQ2GT0P09M" },
    { title: "Paramount", artist: "August Burns Red", album: "Guardians", duration: "04:48", spotifyId: "3xuOmbJpeVFsMY7dh0Pc3e" },
    { title: "Tears Don't Fall", artist: "Bullet For My Valentine", album: "The Poison (Deluxe Version)", duration: "05:48", spotifyId: "3iWlbqAaoIR7H7gyO3a6rV" },
    { title: "Gone with the Wind", artist: "Architects", album: "All Our Gods Have Abandoned Us", duration: "03:45", spotifyId: "6w9PFIfsLZvzo09nfmqjxQ" },
    { title: "Black Lungs", artist: "Architects", album: "For Those That Wish To Exist", duration: "03:51", spotifyId: "06BRkkaJsqM9i6VZKDvUlK" },
    { title: "SLEEPS SOCIETY", artist: "While She Sleeps", album: "SLEEPS SOCIETY", duration: "03:19", spotifyId: "3ZFP6XrE0FHu4duyi7vRoL" },
    { title: "when we were young", artist: "Architects", album: "the classic symptoms of a broken spirit", duration: "03:13", spotifyId: "7DkN4oeXv2mqyPy0sJNrus" },
    { title: "Holy War", artist: "Thy Art Is Murder", album: "Holy War", duration: "04:00", spotifyId: "74SPa1RfRjNh0jj9BYuPxI" },
    { title: "Saint Matthew Returns to the Womb", artist: "Botch", album: "We Are the Romans", duration: "03:04", spotifyId: "0cHb4eJWeqmWKYDRfHJDw9" },
    { title: "One Twenty Two", artist: "Botch", album: "One Twenty Two", duration: "02:16", spotifyId: "1YcAT8wzQpk12OOJcBcOT5" },
    { title: "Break Through It All", artist: "Death Before Dishonor", album: "Count Me In", duration: "03:01", spotifyId: "4WN54cERPExpnOs1adL5nB" },
    { title: "Boltcutter", artist: "Bury Tomorrow", album: "Boltcutter", duration: "03:37", spotifyId: "094hTvgTyLna5FsFulp3DH" },
    { title: "Stick Tight", artist: "Terror", album: "Keepers Of The Faith", duration: "02:33", spotifyId: "6aNAMsKIWJQyexjfCycIVd" },
    { title: "Frequency Ass Bandit", artist: "Botch", album: "We Are the Romans", duration: "04:26", spotifyId: "3DzhBd5meqEmhZrkJoUuXr" },
    { title: "To Our Friends in the Great White North", artist: "Botch", album: "We Are the Romans", duration: "05:11", spotifyId: "2OAod8HcgCJpVEkkT5JdSm" },
    { title: "We Are The Many (Live in Bochum 2012)", artist: "Caliban", album: "Ghost Empire", duration: "04:33", spotifyId: "4J0eSUGtJjrdl5oA5cYBbv" },
    { title: "Voice & Truth", artist: "Bury Tomorrow", album: "Cannibal", duration: "03:06", spotifyId: "1JnCsDspvzS5J0bs5o7OAL" },
    { title: "My Own Grave", artist: "As I Lay Dying", album: "Shaped by Fire", duration: "04:13", spotifyId: "0CcqWuAEJC93K8cBMbAjgI" },
    { title: "Karma", artist: "Parkway Drive", album: "Deep Blue", duration: "03:49", spotifyId: "5fwwWmgreaDgfmLxqOdF8f" },
    { title: "Dying in Your Arms", artist: "Trivium", album: "Ascendancy", duration: "02:53", spotifyId: "2nuA1esWzYEgnfQ4DpsSsm" },
    { title: "Empty Values", artist: "Mindwar", album: "Still At War", duration: "03:11", spotifyId: "4Uhezo22b7Rmeh9ZEkbzo0" },
    { title: "Backfire", artist: "August Burns Red", album: "Death Below", duration: "04:22", spotifyId: "2zd7WJWnvGNNnqnNZ2xzkg" },
    { title: "Blinding Faith", artist: "Knocked Loose", album: "Blinding Faith", duration: "02:51", spotifyId: "5oSnYy4EijgEEEDO9MPDq4" },
    { title: "Calling Hours", artist: "Bane", album: "Don't Wait Up", duration: "04:59", spotifyId: "1yYajBV0wF1IXeJPdtSbHU" },
    { title: "Blackhole", artist: "Architects", album: "Blackhole", duration: "03:20", spotifyId: "2qcXDpEzi89CMgxPXAiiI8" },
    { title: "Whiplash", artist: "Architects", album: "Whiplash", duration: "03:46", spotifyId: "4I5QRJ0vpMpnzR23Lpm3k9" },
    { title: "Belleville", artist: "Knocked Loose", album: "A Different Shade of Blue", duration: "03:16", spotifyId: "7vN4s56DFYoDs7plSPkthe" },
    { title: "Summerholidays Vs. Punkroutine", artist: "Refused", album: "The Shape Of Punk To Come (Deluxe Edition)", duration: "04:03", spotifyId: "6pa63bus7BPu8g8rvJISSj" },
    { title: "NEVER ENOUGH", artist: "Turnstile", album: "NEVER ENOUGH", duration: "04:47", spotifyId: "1zoXDi9AY4TF5JoUuCCTL6" },
    { title: "HOLIDAY", artist: "Turnstile", album: "GLOW ON", duration: "02:52", spotifyId: "1dB0NylVkpjdOe8DiekIs7" },
    { title: "Nobody", artist: "Stick To Your Guns", album: "Disobedient", duration: "03:05", spotifyId: "0oD7vsrHsBHiUMIBEa5EmK" },
    { title: "Suffocate (feat. Poppy)", artist: "Knocked Loose, Poppy", album: "You Won't Go Before You're Supposed To", duration: "02:44", spotifyId: "6PXYOVPBzO3xojFhQAvmde" },
    { title: "Counting Worms", artist: "Knocked Loose", album: "Laugh Tracks", duration: "01:11", spotifyId: "7g3OmlRZ15Gq5Lo3WBMol0" },
    { title: "Choke", artist: "Bury Tomorrow", album: "Cannibal", duration: "03:47", spotifyId: "2KGCOtaTbNIbwrxS0a2UMv" },
    { title: "I CARE", artist: "Turnstile", album: "NEVER ENOUGH", duration: "03:53", spotifyId: "7KVIuHxbV5lvBE5Vyiw8FC" },
    { title: "MYSTERY", artist: "Turnstile", album: "GLOW ON", duration: "02:35", spotifyId: "5iXnD2VizcAbErpkcuNQ6I" },
    { title: "Blood and Thunder", artist: "Mastodon", album: "Leviathan", duration: "03:48", spotifyId: "3jagGO7eHHuaD53ibehkux" },
    { title: "In Waves", artist: "Trivium", album: "In Waves (Special Edition)", duration: "05:02", spotifyId: "1yYr4D1KjhhyDD5bZIiFQy" },
    { title: "Sleepwalker", artist: "Parkway Drive", album: "Deep Blue", duration: "04:01", spotifyId: "2XZP7EIjlD75VwYcHNePYj" },
    { title: "Tears Don't Fall", artist: "Bullet For My Valentine", album: "The Poison", duration: "05:48", spotifyId: "5pKCDm2fw4k6D6C5Rk646C" },
    { title: "The Motherload", artist: "Mastodon", album: "Once More 'Round the Sun", duration: "04:59", spotifyId: "6EF0xhfKtQNqUPz2mnE5BD" },
    { title: "Black Flame", artist: "Bury Tomorrow", album: "Black Flame", duration: "05:18", spotifyId: "26NEy2ZH4PpkMar8l4kEws" },
    { title: "Holy Diver", artist: "Killswitch Engage", album: "As Daylight Dies (Special Edition)", duration: "04:10", spotifyId: "3a9urnht8HvfFzPwd0ipx6" },
    { title: "The End of Heartache", artist: "Killswitch Engage", album: "The End of Heartache (Special Edition)", duration: "04:58", spotifyId: "2nUy0ifVE7UwtOK4rugFsP" },
    { title: "Master of Puppets", artist: "Trivium", album: "Ascendancy (Special Edition)", duration: "08:09", spotifyId: "0P5D7ji9AJi85bEdQhq50a" },
    { title: "LIFE (Paradise Denied)", artist: "Bury Tomorrow", album: "LIFE (Paradise Denied)", duration: "03:31", spotifyId: "3ndwxuh6TAX6eWYy9jWwhP" },
    { title: "You Want a Battle? (Here's a War)", artist: "Bullet For My Valentine", album: "Venom (Deluxe Edition)", duration: "04:14", spotifyId: "1KCAEG6JcsTzi8ddZzs0nk" },
    { title: "Until the World Goes Cold", artist: "Trivium", album: "Silence in the Snow", duration: "05:21", spotifyId: "0ncHMpFGT96pis5pi4iJDm" },
    { title: "Always The Hard Way", artist: "Terror", album: "Always the Hard Way", duration: "02:33", spotifyId: "3ZQTm3sUohmXP3cU44WGa6" },
    { title: "Anger", artist: "Downset", album: "Downset", duration: "04:13", spotifyId: "3Biz0iz1YTAyDXed2hrgm1" },
    { title: "Dark Horse", artist: "Converge", album: "Axe To Fall", duration: "02:54", spotifyId: "4bDHr5yOmdI2nmbWvBpPS2" },
    { title: "Almost Easy", artist: "Avenged Sevenfold", album: "Avenged Sevenfold", duration: "03:54", spotifyId: "0DkmhHO4yyqCJFjosmmWPU" },
    { title: "The Pretender", artist: "Foo Fighters", album: "Echoes, Silence, Patience & Grace", duration: "04:29", spotifyId: "7x8dCjCr0x6x2lXKujYD34" },
    { title: "Everlong", artist: "Foo Fighters", album: "The Colour And The Shape", duration: "04:10", spotifyId: "5UWwZ5lm5PKu6eKsHAGxOk" },
    { title: "Everlong - Acoustic Version", artist: "Foo Fighters", album: "Greatest Hits", duration: "04:10", spotifyId: "3QmesrvdbPjwf7i40nht1D" },
    { title: "Best of You", artist: "Foo Fighters", album: "In Your Honor", duration: "04:15", spotifyId: "5FZxsHWIvUsmSK1IAvm2pp" },
    { title: "Learn to Fly", artist: "Foo Fighters", album: "There Is Nothing Left To Lose", duration: "03:55", spotifyId: "5OQsiBsky2k2kDKy2bX2eT" },
    { title: "Walk", artist: "Foo Fighters", album: "Wasting Light", duration: "04:15", spotifyId: "76Je5Wklky23mVoxiRszcN" },
    { title: "Smells Like Teen Spirit", artist: "Nirvana", album: "Nevermind (Deluxe Edition)", duration: "05:01", spotifyId: "1f3yAtsJtY87CTmM8RLnxf" },
    { title: "About A Girl - Remastered", artist: "Nirvana", album: "Bleach: Deluxe Edition", duration: "02:48", spotifyId: "0zeqKbySjKbfW5jyl3PMsW" },
    { title: "Come As You Are", artist: "Nirvana", album: "Nevermind (Deluxe Edition)", duration: "03:38", spotifyId: "0MKGH8UMfCnq5w7nG06oM5" },
    { title: "Heart-Shaped Box", artist: "Nirvana", album: "In Utero - 20th Anniversary - Deluxe Edition", duration: "04:41", spotifyId: "4OaV9UYQ3EfrBRPjoO6u7c" },
    { title: "Lithium", artist: "Nirvana", album: "Nevermind (Deluxe Edition)", duration: "04:17", spotifyId: "26D1PRJjD9Jj1JGRk88KVc" },
    { title: "The Man Who Sold The World", artist: "Nirvana", album: "MTV Unplugged In New York", duration: "04:20", spotifyId: "48psxWnIVYCPUZJKiuDiEf" },
    { title: "Come As You Are", artist: "Nirvana", album: "MTV Unplugged In New York", duration: "04:13", spotifyId: "4yzgjSHWy5E8fKflgwaKQh" },
    { title: "Lake Of Fire", artist: "Nirvana", album: "MTV Unplugged In New York", duration: "02:55", spotifyId: "3aKJVWH2QOsaMtiCLxYHZX" },
    { title: "Rape Me", artist: "Nirvana", album: "In Utero - 20th Anniversary - Deluxe Edition", duration: "02:50", spotifyId: "11Tm0hw3DDF1gqU0kSEwiC" },
    { title: "In Bloom", artist: "Nirvana", album: "Nevermind (Remastered)", duration: "04:15", spotifyId: "30HCB1FoE77IfGRyNv4eFq" },
    { title: "All My Life", artist: "Foo Fighters", album: "One By One", duration: "04:22", spotifyId: "40Gxnw5Vc8hnhGFknXHe3R" },
    { title: "All Apologies - Live", artist: "Nirvana", album: "MTV Unplugged In New York", duration: "04:23", spotifyId: "3bH8PZsfbCRIoeNiFm7JmU" },
    { title: "Drain You", artist: "Nirvana", album: "Nevermind (Remastered)", duration: "03:43", spotifyId: "5Ddlk6C2JVxb1SReZ6O1wk" },
    { title: "Give It Away", artist: "Red Hot Chili Peppers", album: "Blood Sugar Sex Magik (Deluxe Edition)", duration: "04:42", spotifyId: "0uppYCG86ajpV2hSR3dJJ0" },
    { title: "Times Like These", artist: "Foo Fighters", album: "One By One", duration: "04:25", spotifyId: "2ql32BJPN3hnyboml4JfER" },
    { title: "Dumb - Live", artist: "Nirvana", album: "MTV Unplugged In New York", duration: "02:52", spotifyId: "725QAOexNLmGZiFMN7U8pF" },
    { title: "Polly - Live", artist: "Nirvana", album: "MTV Unplugged In New York", duration: "03:16", spotifyId: "0xHch89AN9RlN8Nm4kJzs3" },
    { title: "About A Girl - Live", artist: "Nirvana", album: "MTV Unplugged In New York", duration: "03:38", spotifyId: "48YkpE5enOln5c7jXSTuHL" },
    { title: "Higher Ground - Remastered 2003", artist: "Red Hot Chili Peppers", album: "Mother's Milk", duration: "03:22", spotifyId: "5arVt2Wg0zbiWwAOZef2Nl" },
    { title: "Come As You Are", artist: "Nirvana", album: "Nevermind (Remastered)", duration: "03:38", spotifyId: "2RsAajgo0g7bMCHxwH3Sk0" },
    { title: "Smells Like Teen Spirit", artist: "Nirvana", album: "Nevermind (Remastered)", duration: "05:01", spotifyId: "4CeeEOM32jQcH3eN9Q2dGj" },
    { title: "Lithium", artist: "Nirvana", album: "Nevermind (Remastered)", duration: "04:17", spotifyId: "5vHLwhxxlGzmClMcxRRFPr" },
    { title: "Dumb", artist: "Nirvana", album: "In Utero", duration: "02:31", spotifyId: "5gRcv46AMTrosmTOqrOV3Q" },
    { title: "Lake Of Fire - Live", artist: "Nirvana", album: "MTV Unplugged In New York", duration: "02:55", spotifyId: "4UJmPSJsBsIR1U0N79BU1g" },
    { title: "Something In The Way", artist: "Nirvana", album: "Nevermind (Remastered)", duration: "03:52", spotifyId: "4gHnSNHs8RyVukKoWdS99f" },
    { title: "In Bloom", artist: "Nirvana", album: "Nevermind (Remastered)", duration: "04:15", spotifyId: "2mvffzYUJ9Ld9xhsF5DUjU" },
    { title: "Drain You", artist: "Nirvana", album: "Nevermind (Remastered)", duration: "03:43", spotifyId: "0bTLGlCqwZXwJGWGE2Dywg" },
    { title: "Tell Me Baby", artist: "Red Hot Chili Peppers", album: "Stadium Arcadium", duration: "04:07", spotifyId: "0itNMuBHye9fu392b4e9oa" },
    { title: "Around the World", artist: "Red Hot Chili Peppers", album: "Californication (Deluxe Edition)", duration: "03:58", spotifyId: "0aGQHMr7bc23Y9Ts84ffop" },
    { title: "Road Trippin'", artist: "Red Hot Chili Peppers", album: "Californication", duration: "03:24", spotifyId: "7Gpr3kKk4BMgItz6UbI73q" },
    { title: "Times Like These", artist: "Foo Fighters", album: "One By One (Expanded Edition)", duration: "04:25", spotifyId: "67vYdAAM3oGsEImCRfbtsF" },
    { title: "Buddy Holly", artist: "Weezer", album: "Weezer", duration: "02:39", spotifyId: "3mwvKOyMmG77zZRunnxp9E" },
    { title: "Africa", artist: "Weezer", album: "Weezer (Teal Album)", duration: "03:58", spotifyId: "3ZPKocroJIcnHGcnJVlLKD" },
    { title: "Happy Together", artist: "Weezer", album: "Weezer (Teal Album)", duration: "02:25", spotifyId: "3KxOYNt66Hj42HzO7ao0CV" },
];